### ISSUE TITLE
green cards are white

### ISSUE THREAD

**Issue by Iaiz** [Nickardson/shenzhen-solitaire#4]
all of the symbols on the green cards are white, making it hard to see. is there a fix for this?
![screen shot 2019-02-26 at 3 38 31 pm](https://user-images.githubusercontent.com/48033714/53448270-9d877780-39dc-11e9-8f4d-da7dc6d6d98a.png)

**Comment by Nickardson** [comment]
Thanks for opening this. Looks like the game changed the bamboo graphics to be white a while back.
I still like the simplicity of dropping in the game assets unchanged, so I added a somewhat hacky way of recoloring the assets in the browser, which doesn't require any manual editing.

**Comment by Iaiz** [comment]
thanks!
