### ISSUE TITLE
Special card backs tile instead of showing whole image

### ISSUE THREAD

**Issue by BenPryorARC** [Nickardson/shenzhen-solitaire#8]
The special card backings (for 100+ wins), are tiling instead of showing the single image on the back of the card. See [here](https://i.imgur.com/4C3CShK.png) (500% zoom). I'm not sure whether or not this is intentional, I'm just assuming it's not.

Browser: Chrome 97.0.4692.71

**Comment by Nickardson** [comment]
Thanks for the bug report!
